server:
  port: 8762

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/smile2sm/springcloud.git/
          username: smile2.sm@qq.com
          password: gan13878533932
          search-paths: /SpringCloudConfig/springconfig
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/